version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: "[Dependabot]"
      include: scope
    open-pull-requests-limit: 10
    target-branch: develop
