apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: template-api-go
  name: template-api-go
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: template-api-go
  strategy: { }
  template:
    metadata:
      labels:
        app: template-api-go
    spec:
      containers:
        - image: ${docker_registry}/it/template-api-go
          name: template-api-go
          imagePullPolicy: Always
          resources: { }
          envFrom:
            - secretRef:
                name: template-api-go
          readinessProbe:
            httpGet:
              path: /template-api-go/healthz
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 5
            successThreshold: 1
          livenessProbe:
            httpGet:
              path: /template-api-go/healthz
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 60
            timeoutSeconds: 5
            failureThreshold: 3
            successThreshold: 1
          volumeMounts:
            - mountPath: /app/log
              name: log-volume
      volumes:
        - name: log-volume
          hostPath:
            path: /var/log/deployments/template-api-go
      tolerations:
        - key: "node.kubernetes.io/memory-pressure"
          operator: "Exists"
          effect: "NoSchedule"
        - key: "node.kubernetes.io/not-ready"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 0
        - key: "node.kubernetes.io/unreachable"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 0
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/path: /template-api-go/metrics
    prometheus.io/port: "8080"
    prometheus.io/scrape: "true"
  labels:
    app: template-api-go
  name: template-api-go
  namespace: default
spec:
  ports:
    - name: 8080-8080
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: template-api-go
  type: ClusterIP
status:
  loadBalancer: { }