name: SAST scan workflow

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  scan:
    name: CodeQL Scan
    runs-on: ubuntu-latest
    strategy:
      matrix:
        language: [ "javascript" ]
        node-version: [ 22.x ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: CodeQL init
        uses: github/codeql-action/init@v3
        with:
          build-mode: autobuild
          languages: ${{ matrix.language }}
      - name: CodeQL Analysis
        uses: github/codeql-action/analyze@v3
